
[Network]
num_wires = 2000
area = 1000.0
length = 70.0
proximity_threshold_ratio = 0.05

[Electrical]
v_input = 3.6
v_ground = 0.0
# Guardamos los parámetros físicos para calcular R de forma exacta en el script
rho_plata = 0.0159
diametro_nm = 115.0

[Time]
total_time = 0.5
time_step_dt = 1e-3

[Memristor]
g_on = 1e-3
g_off = 1e-9
v_threshold = 0.01

[Probabilities]
p0_set = 0.4
alpha_set = 1.0
p_decay = 0.8
beta_reset = 1.0